[Proxies]
# This property is used by the clients to connect to IceStorm.
TopicManager = "IceStorm/TopicManager:default -p 9999"

# Proxies for publishes interfaces
FullPoseEstimationPubPrefix = ""


[Endpoints]
# Endpoints for subscriptions interfaces
JoystickAdapterTopic = "tcp -p 11025"
JoystickAdapterPrefix = ""

# Endpoints for implements interfaces
Camera360RGB = "tcp -p 10098"
CameraRGBDSimple = "tcp -p 10096"
IMU = "tcp -p 10007"
Laser = "tcp -p 10003"
Lidar3D = "tcp -p 11988"
OmniRobot = "tcp -p 10004"
VisualElements = "tcp -p 10005"
Webots2Robocomp = "tcp -p 10006"




[Period]
Compute = 10
Emergency = 500

[Ice]
Warn.Connections = "0"
Trace.Network = "0"
Trace.Protocol = "0"
MessageSizeMax = "20004800"
